### ISSUE TITLE
Datasets used for producing speedup benchmarks acceleration

### ISSUE THREAD

**Issue by vineel96** [intel/scikit-learn-intelex#1272] opened 2023-05-04 05:08 UTC
Hello,
Can I get the information of datasets used for producing benchmark results(speedup values) for different scikit-learn algorithms as shown in figure under Acceleration sub section. Image is also attached here:
![scikit-learn-acceleration-2021 2 3](https://user-images.githubusercontent.com/16516666/236116664-4fc1d762-da8e-4298-b236-8d4c861a9304.png)

**Comment by Alexsandruss** [comment] 2023-05-05 07:31
Duplicate of https://github.com/IntelPython/scikit-learn_bench/issues/135

**Closed by Alexsandruss** 2023-05-05 07:31 UTC
