### ISSUE TITLE
WARNING:root:Device support is limited. Please install dpctl for full experience

### ISSUE THREAD

**Issue by majsterkovic** [intel/scikit-learn-intelex#1241] opened 2023-04-15 17:47 UTC
**Describe the bug**
WARNING:root:Device support is limited. Please install dpctl for full experience
```
RuntimeError: Device support is not implemented
```

**To Reproduce**

```py
with config_context(target_offload="gpu:0"):
    grid_search = GridSearchCV(pipeline, params)
    grid_search.fit(X_train, y_train)
```

**Output/Screenshots**
```ps
PS > python --version
Python 3.9.0
PS > pip install dpctl
Requirement already satisfied: dpctl in c:\users\...\appdata\local\programs\python\python39\lib\site-packages (0.11.3)
```

**Environment:**
 - OS: Windows 11
 - Compiler: Python 3.9 
 - Version: Jupyter Kernel
 - Intel Core i5-1135G7
 - Intel oneAPI installed

**Comment by Alexsandruss** [comment] 2023-04-15 19:34
`0.11.3` version of dpctl is outdated. Newer ones (0.14.*) are availble on [`intel`](https://anaconda.org/intel/dpctl) and [`dppy`](https://anaconda.org/dppy/dpctl) conda channels

**Comment by majsterkovic** [comment] 2023-04-15 19:54
> `0.11.3` version of dpctl is outdated. Newer ones (0.14.*) are available on [`intel`](https://anaconda.org/intel/dpctl) and [`dppy`](https://anaconda.org/dppy/dpctl) conda channels

This version was installed by pip.
I don't use the conda manager. Can I download the .whl file?

**Comment by majsterkovic** [comment] 2023-04-15 21:05
@Alexsandruss
I've updated it manually but `RuntimeError: Device support is not implemented` still occurs.

**Comment by Alexsandruss** [comment] 2023-04-16 11:01
> > `0.11.3` version of dpctl is outdated. Newer ones (0.14.*) are available on [`intel`](https://anaconda.org/intel/dpctl) and [`dppy`](https://anaconda.org/dppy/dpctl) conda channels
> 
> This version was installed by pip. I don't use the conda manager. Can I download the .whl file?

dpctl wheels newer than 0.11 are not available. Issue connected to update of PyPI packages (https://github.com/IntelPython/dpctl/issues/940) is not addressed yet.

**Comment by Alexsandruss** [comment] 2023-04-16 11:04
I used context successfully with next conda installation (DPC++ runtimes are also required):
```
conda create -n test -c conda-forge -c intel python=3.9 scikit-learn-intelex=2023.1 dpctl=0.14 dpcpp-cpp-rt=2023.1
```
float64 type is not supported on this GPU, so you will need to convert data:
```python
x = x.astype('float32')
```

**Comment by majsterkovic** [comment] 2023-04-17 22:16
Steps for reproduce:
```ps
> conda create -n test -c conda-forge -c intel python=3.9 scikit-learn-intelex=2023.1 dpctl=0.14 ?> dpcpp-cpp-rt=2023.1 ipykernel```
> conda activate test
> jupyter notebook
```
Run jupyter notebook

Actual result:
```RuntimeError: Device support is not implemented```

I modified my code to operate on arrays of type float32.

**Comment by Alexsandruss** [comment] 2023-04-18 14:15
Did you install latest (2023.1.0) oneAPI toolkit?
Is GPU device visible in dpctl: `import dpctl; print(list(filter(lambda x: x.is_gpu, dpctl.get_devices())))`?

**Comment by majsterkovic** [comment] 2023-04-18 19:18
I sincerely thank you for your reply, @Alexsandruss.

Yes, I did.

<img src="https://user-images.githubusercontent.com/29355048/232878586-930378e2-0ef8-45bb-8e1d-a05f4dda6f68.png" width="400">
<img src="https://user-images.githubusercontent.com/29355048/232878490-2d05088a-ab93-4eb3-9cfc-b621ec27fe14.png" width="400">

```cmd
>conda activate test
>REM The OpenCL loader ignores value of this variable if running with elevated privileges
>set "OCL_ICD_FILENAMES=C:\Users\...\anaconda3\envs\test\Library\lib\intelocl64.dll"
(test) >set "OCL_ICD_FILENAMES=C:\Users\Mariusz\anaconda3\envs\test\Library\lib\intelocl64.dll"
(test) >
(test) >python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dpctl; print(list(filter(lambda x: x.is_gpu, dpctl.get_devices())))
[<dpctl.SyclDevice [backend_type.opencl, device_type.gpu,  Intel(R) Iris(R) Xe Graphics] at 0x24e88a24f70>]
```

It seems that the GPU is not "seen" in the jupyter notebook, even though I booted it through the terminal with the conda environment activated.
Do you have any idea how I can check this, maybe the wrong kernel is being used? Maybe I am launching the notebook itself wrong?

**Comment by Alexsandruss** [comment] 2023-04-19 08:30
If GPU is not available only in interactive kernel, you are probably running notebook from another Python environment.
I don't see any difference between CLI and notebook on my machine:
![image](https://user-images.githubusercontent.com/24354279/233016509-76d10637-dba1-4761-902a-c8497c2258b9.png)

**Comment by majsterkovic** [comment] 2023-04-19 09:16
![image](https://user-images.githubusercontent.com/29355048/233028667-04be2314-e9f2-457f-9d4e-49abb906bacb.png)
![image](https://user-images.githubusercontent.com/29355048/233028819-08b1ae2f-ffe4-469e-881d-38e5ce7ed05a.png)
![image](https://user-images.githubusercontent.com/29355048/233028916-b25c5dc3-a255-43f4-894c-4c4917f91199.png)

**Comment by Alexsandruss** [comment] 2023-04-20 10:18
Issue is caused by running of model inference outside of GPU context. Awaiting for update of documentation about this behavior to close this.

**Comment by Alexsandruss** [comment] 2023-05-05 08:29
Update of docs: https://github.com/intel/scikit-learn-intelex/pull/1275

**Closed by Alexsandruss** 2023-05-05 08:29 UTC
Labels: bug
