### ISSUE TITLE
SVM models trained with sparse matrix cannot be serialized (pickled)

### ISSUE THREAD

**Issue by yappyjp** [intel/scikit-learn-intelex#1005] opened 2022-05-16 06:54 UTC
**Describe the bug**
SVC model trained with a scipy sparse matrix cannot be serialized (pickled).

**To Reproduce**
```
#!/usr/bin/env python

import sklearn.svm
from sklearn import datasets
import scipy.sparse
import pickle

X, y = datasets.load_iris(return_X_y=True)

## with numpy array
clf = sklearn.svm.SVC()
clf.fit(X, y)

## OK. no problem
s = pickle.dumps(clf)

## with Sparse matrix
X = scipy.sparse.csr_matrix(X)
clf = sklearn.svm.SVC()
clf.fit(X, y)

# Error 
s = pickle.dumps(clf)
```
```
Traceback (most recent call last):
  File "**.py", line 24, in <module>
    s = pickle.dumps(clf)
ValueError: Object is not serializable
```

**Environment:**
 - Intel distribution for Python 2022.2.0 (installed via dnf).

**Comment by PivovarA** [comment] 2022-05-23 09:09
Hi @yappyjp 
Thanks for pointing out this issue. 
I'll check what could be the cause and get back as soon as I can

**Comment by Alexsandruss** [comment] 2022-07-29 12:36
It appears that internal oneDAL model with sparse data usage is the reason.
Trying to serialize `clf._onedal_estimator._onedal_model` with fail with same error.

**Comment by Alexsandruss** [comment] 2022-08-11 09:16
Same error without https://github.com/oneapi-src/oneDAL/pull/2122 fix will appear for any patched SVM model - NuSVC/NuSVR/SVC/SVR.

**Comment by doganMemory** [comment] 2022-09-29 08:02
Hi!
Is there any update on this one? I saw the [PR](https://github.com/oneapi-src/oneDAL/pull/2122) is approved but nor merged yet?

**Comment by Alexsandruss** [comment] 2022-09-29 09:03
Hi @doganMemory, [PR](https://github.com/oneapi-src/oneDAL/pull/2122) is waiting for additional approval and check

**Comment by arijit-s** [comment] 2022-12-28 17:10
@Alexsandruss The above PR is merged it seems. When can it be merged into the intelex package?

**Comment by napetrov** [comment] 2022-12-28 17:16
@arijit-s  - this have been released already - you can look for latest package on pypi/conda

**Closed** 2023-05-05 09:30 UTC
Labels: bug
