### ISSUE TITLE
Building oneDAL with icpx Compiler Fails to Build scikit-learn-intelex Patch

### ISSUE THREAD

**Issue by rakshithgb-fujitsu** [intel/scikit-learn-intelex#1981] opened 2024-07-31 09:19 UTC
### **Description:**

I'm encountering an issue when building this intelex patch when using oneDAL built with `icpx` compiler.

### **Environment:**

Compiler: icpx
Python version: 3.10
Platform: Linux (x86_64)

### **Steps to Reproduce:**
Use the following make command to build oneDAL:
```
make -f makefile daal oneapi_c BACKEND_CONFIG=mkl ARCH=32e PLAT=lnx32e COMPILER=icx -j$(nproc)
```
Attempt to build the scikit-learn-intelex patch using:
```
python3.10 setup.py install --single-version-externally-managed --record=record.txt
```

### **Expected Result:**
The scikit-learn-intelex patch should build successfully without any errors.

### **Actual Result:**
The build process fails with the following error messages:

```
[100%] Linking CXX shared module _onedal_py_dpc.cpython-310-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -l:libonedal_dpc.so.2: No such file or directory
/usr/bin/ld: cannot find -l:libonedal_parameters_dpc.so.2: No such file or directory
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/_onedal_py_dpc.dir/build.make:513: _onedal_py_dpc.cpython-310-x86_64-linux-gnu.so] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/_onedal_py_dpc.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```
### **Additional Information:**

- The error indicates missing libraries: `libonedal_dpc.so.2` and `libonedal_parameters_dpc.so.2`. These libraries are not generated during the oneDAL build process.
- The patch builds successfully when using the GNU compiler.

**Comment by ethanglaser** [comment] 2024-08-05 15:24
Hi @rakshithgb-fujitsu, there are 2 options based on your situation:

1. You intend to build full scope (or at least dpc backend) of sklearnex: in this case the OneDAL build command is not sufficient because onedal dpc libs are required - you can modify `make -f makefile daal oneapi_c BACKEND_CONFIG=mkl ARCH=32e PLAT=lnx32e COMPILER=icx -j$(nproc)` to instead be `make -f makefile onedal_dpc BACKEND_CONFIG=mkl ARCH=32e PLAT=lnx32e COMPILER=icx -j$(nproc)`
2. You intend to only build host backend for sklearnex: in this case there may be a change from our side required to allow for sklearnex build without dpc backend

Please let me know if #2 applies - if so I can look into reproducing and providing a conditional in sklearnex that will not require dpc.

**Comment by rakshithgb-fujitsu** [comment] 2024-08-07 06:41
@ethanglaser thanks for the inputs, yes building with `onedal_dpc` option works. It would be nice to have the second option implemented as well, I see a new pull request for this. Will wait for the fix in meantime.

**Comment by rakshithgb-fujitsu** [comment] 2024-08-07 06:51
@ethanglaser though build step works, during runtime I get import errors:
```
from daal4py._daal4py import *
ImportError: libsvml.so: cannot open shared object file: No such file or directory
```

**Comment by Alexsandruss** [comment] 2024-08-08 09:15
Building oneDAL with icx leads to dependency on some compiler shared libs. This dependency is inherited by daal4py shared library. I guess it will be fixed by linking options in oneDAL and/or daal4py.

**Comment by Alexsandruss** [comment] 2024-08-08 17:07
Fixed by https://github.com/oneapi-src/oneDAL/pull/2870.

**Closed by Alexsandruss** 2024-08-08 17:07 UTC
Labels: bug
