### ISSUE TITLE
Question: Identity of the Dataset

### ISSUE THREAD

**Issue by shashank-fujitsu** [intel/scikit-learn-intelex#1273] opened 2023-05-04 06:02 UTC
Hi,
I would like to know,
- What are the datasets used for the graph below?
- What version of Scikit-Learn is used of comparison? 

![image](https://user-images.githubusercontent.com/130481473/236122977-07796457-a80f-465f-9757-ce76dd7e09b6.png)

**Comment by Alexsandruss** [comment] 2023-05-05 07:31
Duplicate of https://github.com/IntelPython/scikit-learn_bench/issues/135

Configuration was shown below graph:
```
Configurations:

HW: c5.24xlarge AWS EC2 Instance using an Intel Xeon Platinum 8275CL with 2 sockets and 24 cores per socket
SW: scikit-learn version 0.24.2, scikit-learn-intelex version 2021.2.3, Python 3.8
```

**Closed by Alexsandruss** 2023-05-05 07:31 UTC
